# A.Creating and Saving Numpy ndarrays

1. Create some array object based on the following requirement below:

In [ ]:
#import numpy
import numpy as np

# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print(z)

2. We create a rank 1 ndarray of floats but set the dtype to int64.

In [ ]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1, 2, 3, 4, 5], dtype = np.float64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)

3. Create, save and then load it to a array object toa file and use it later.

In [ ]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)


In [ ]:
y = np.load('my_array.npy')
print(y)

# B.Using Built-in Functions to create ndarrays

1. Create a numpy array of strings containing letters 'a' through 'j' (inclusive) of the alphabet. Then, use numpy array attributes to print the following information about this array:
dtype of array,
shape of array,
size of array,


In [ ]:
import numpy as np

# create numpy array of letters a-j
list_chars =  [chr(i) for i in range(97,107)]
    
letter_array = np.array(list_chars)
print("Letter Array: ", letter_array)

# get dtype of array
print(letter_array.dtype)

# get shape of array
print(letter_array.shape)


# get size of array
print(letter_array.size)

2. Using Numpy's functions to create 2D array with all elements equal to 0 (int) and 1.(float).


In [ ]:
#2D array with all element equal to 0
x =  np.zeros((3,4), dtype=int)
print(x)

#2D array with all element equal to 1
y = np.ones((3,4))
print(y)


3. Using function np.full() to create 3x5 2Darray with all elements equal to 10

In [ ]:
z = np.full((3,5), 6)
print(z)

4. create a identity matrix 5x5 with all elements equal to 0 except value in diagonal (equal to 1).

In [ ]:
square_array = np.eye(5, dtype=int)
print(square_array)

5. Create a 6x6 diagonal matrix with value in diagonal equal to 10, 20, 30, 40, 50, 60 chronically.

In [ ]:
diagonal_matrix = np.diag([10,20,30,40,50,60])
print(diagonal_matrix)

6. Using the Built-in functions you learned about in the
previous lesson, create a 4 x 4 ndarray that only
contains consecutive even numbers from 2 to 32 (inclusive)

In [ ]:
import numpy as np
# using np.arange() method
x = np.arange(2, 33, 2).reshape(4,4)
print(x)

# using np.linspace() method
y = np.linspace(2,32, 16).reshape(4,4)

print(y)

6. Create 3x3 array with random elements (float).

In [ ]:
random_array = np.random.random((3,3))
print(random_array)

7. Create 5x6 array with random elements within a range that we define.

In [ ]:
random_array = np.random.randint(0,5, (5,6))
print(random_array)

8. Create a 4x4 ndarray with the average of all elements equal to 1 and standard deviation 0.1

In [ ]:
X = np.random.normal(1, 0.1, size=(4,4))

print(X)
print('An array has total {} elements > 1'.format((X > 1).sum()))
print('An array has total {} elements < 1'.format((X < 1).sum()))
print('the average of x: ', X.mean())
print('Biggest value in array:', X.max())
print('Smallest value in array:', X.min())

# C. Accessing, deleting and inserting elements into ndarrays 

1. Extract value from 1D and 2D array.

In [ ]:
#Extract element's value at index=5 from 1D array
rank1_array = np.arange(10)
print(rank1_array)
print('Value of element has index = 5 equal to: {}'.format(rank1_array[5]), '\n')

#Extract element's value at (1st row and 2nd column) , (2nd row and 3nd column)  from 2D array
rank2_array = np.arange(15).reshape(3,5)
print(rank2_array)
print('value at 1st row and 2nd column is: {}'.format(rank2_array[0,1]))
print('value at 2nd row and 3nd column is: {}'.format(rank2_array[1,2]))


2. Delete elememts from 1D array and 2D array.

In [ ]:
# Delete the first and the last elements at from 1D array.
r1_array = np.arange(10)
print('initial 1D array: ', r1_array)

r1_array = np.delete(r1_array, [0, -1])
print('1D array after remove elements:', '\n', r1_array)

# Delete multi rows in 2D array
r2_array1 = np.arange(10).reshape(5,2)
print('initial 2D array: ', '\n', r2_array)

r2_array1 = np.delete(r2_array1, [0,2], axis = 0)
print('2D array after remove 1st . 3nd rows:', '\n', r2_array1)

## Delete multi column in 2D array
r2_array2 = np.arange(10).reshape(2,5)
print('initial 2D array: ', '\n', r2_array2)

r2_array2 = np.delete(r2_array2, [1, -1], axis = 1)
print('2D array after remove 2nd , last column:', '\n', r2_array2)

3. Append value to ndarrays

In [ ]:
#Create 3x3 array
x = np.arange(1,10).reshape(3,3)
print('Origional array: \n', x)

#append two new rows
y = np.append(x, [[10,11,12], [11,32,31]], axis=0)
print('Array after append a row:\n', y)

#append two new columns
z = np.append(x, [[13, 22 [14, 16], [15, 5]] ,axis=1)
print('Array after append a column:\n', z)


4. Using vstack function to perform NDarray.

In [ ]:
# We create a rank 1 ndarray 
x = np.array([[1,2], [9,0]])
# We create a rank 2 ndarray 
y = np.array([3,4])

z = np.vstack((x, y))
print('After stack two 2 arrays of x and y:', '\n', z)


5. Using hstack function to perform NDarray.

In [ ]:
# We create a rank 2 ndarray 
x = np.array([[1,2], [3,4], [5,6]])


# We create a rank 1 ndarray 
y = np.array([5,6,7])

#hstack of x and y.
z = np.hstack((x, y.reshape(3,1)))
print('After stack two 2 arrays of x and y:', '\n', z)


# D. Slicing ndarrays

1. Create 2nd array (4x5) and perform at 3 slices then save it into new variables.

In [ ]:
#Create 4x5 array
X = np.arange(20).reshape(4,5)
print(X, '\n')

#Use slicing to get 1st column and 2nd column in X
Y = X[:, 1:3]
print('Array Y (a view from orginal array X): ','\n', Y)

#Use slicing to get the last two rows of X but just contains only the last two columns in X
Z = X[2:, 3:]
print('Array Z (a view from orginal array X): ','\n', Z)

#Use slicling to get only 4th columns of X
W = X[:, 3:4]
print('Array W (a view from orginal array X): ','\n', W)


2. Using np.copy() function to create and save a copied slice to a new variable. Try to change  the element in new varibale to see whether it changes the value in orginal array or not.

In [ ]:
#Create 4x6 array
X = np.arange(24).reshape(4,6)
print('riginal array X: ', '\n', X)

#Using copy function to have a new variable from the orginal one, not just a view.
Y = X[1:, 3:].copy()
print('independent array Y: ','\n', Y)

#change value in array Y and test whether it also changes in orginal array X or not.
Y[0, 2] = 12
print('array Y after change: ', '\n', Y)
print('Original array X after change element in array Y: ', '\n', X)



3. Using 1D array to make slices, select or change elements in other array

In [ ]:
#Create 1D array as an indices
indices = np.array([1,3])

#create 2D 4x5 array.
array = np.arange(20).reshape(4,5)
print('array: ', '\n', array)

#Use indices to get 2nd and 4th rows in array
x = array[indices, :]
print('array x contains 2nd and 4th rows in array: ', '\n', x)

#Use #Use indices to get 2nd and 4th columns in array
y = array[:, indices]
print('array y contains 2nd and 4th columns in array: ', '\n', y)


4. Using function np.diag() to extract the value of the main diagonal or the value of the above, below diagonals.

In [ ]:
#Create a 6x6 array
x = np.arange(36).reshape(6,6)
print('x: ', '\n', x)

#extract elements lie on the main diagonal
main_diag = np.diag(x)
print('elements in the main diagonal:' ,main_diag)

#extract elements of the diagonal which is above the main diagonal.
above1_diag = np.diag(x, k=1)
print('the 1st diagonal above the main diagonal: ', above1_diag)
above2_diag = np.diag(x, k=2)
print('the 2nd diagonal above the main diagonal: ', above2_diag)

#extract elements of the diagonal which is below the main diagonal.
below1_diag = np.diag(x, k=-1)
print('the 1st diagonal below the main diagonal: ', below1_diag)
below2_diag = np.diag(x, k=-2)
print('the 2nd diagonal below the main diagonal: ', below2_diag)


5. Extract unique value from  ndarray using built-in function

In [6]:
import numpy as np
#create 4x4 array with duplicates
x = np.array([[1,2,3,1],[4,3,7,8],[4,1,78,1],[1,2,4,2]]).reshape(4,4)
print(x)

#extract unique values.
print('unique value: ',np.unique(x))

[[ 1  2  3  1]
 [ 4  3  7  8]
 [ 4  1 78  1]
 [ 1  2  4  2]]
unique value:  [ 1  2  3  4  7  8 78]
